"""empty message

Revision ID: 35a11962d33a
Revises: 542aeef343a3
Create Date: 2015-05-04 20:19:38.756491

"""

# revision identifiers, used by Alembic.
revision = '35a11962d33a'
down_revision = '542aeef343a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('entry_num', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'entry_num')
    ### end Alembic commands ###
