"""empty message

Revision ID: 542aeef343a3
Revises: 61b98a362d2
Create Date: 2015-05-03 20:32:18.402841

"""

# revision identifiers, used by Alembic.
revision = '542aeef343a3'
down_revision = '61b98a362d2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'journals_journal_id_fkey', 'journals', type_='foreignkey')
    op.drop_column('journals', 'journal_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journals', sa.Column('journal_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'journals_journal_id_fkey', 'journals', 'entries', ['journal_id'], ['id'])
    ### end Alembic commands ###
