"""empty message

Revision ID: 61b98a362d2
Revises: 1325821d7c7b
Create Date: 2015-05-03 20:15:40.848840

"""

# revision identifiers, used by Alembic.
revision = '61b98a362d2'
down_revision = '1325821d7c7b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'entries', sa.Column('journal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'entries', 'journals', ['journal_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entries', type_='foreignkey')
    op.drop_column(u'entries', 'journal_id')
    op.drop_table('journals')
    ### end Alembic commands ###
